api quasi fonctionnel
btp_api  |
btp_api  | > inframusicstore-api@1.0.0 start
btp_api  | > node src/app.js
btp_api  |
btp_api  | node:internal/modules/cjs/loader:1210
btp_api  |   throw err;
btp_api  |   ^
btp_api  |
btp_api  | Error: Cannot find module './route/artists'
btp_api  | Require stack:
btp_api  | - /app/src/app.js
btp_api  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
btp_api  |     at Module._load (node:internal/modules/cjs/loader:1038:27)
btp_api  |     at Module.require (node:internal/modules/cjs/loader:1289:19)
btp_api  |     at require (node:internal/modules/helpers:182:18)
btp_api  |     at Object.<anonymous> (/app/src/app.js:17:25)
btp_api  |     at Module._compile (node:internal/modules/cjs/loader:1521:14)
btp_api  |     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
btp_api  |     at Module.load (node:internal/modules/cjs/loader:1266:32)
btp_api  |     at Module._load (node:internal/modules/cjs/loader:1091:12)
btp_api  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12) {
btp_api  |   code: 'MODULE_NOT_FOUND',
btp_api  |   requireStack: [ '/app/src/app.js' ]
btp_api  | }
btp_api  |
btp_api  | Node.js v20.19.5